version: '3.9'
services:
  postgres-db:
    env_file:
      - .env
    image: 'postgres:14.3'
    volumes:
      - liquibase-test:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  liquibase-test:
    driver: local
